version: '3.8'

networks:
  animals:

services:

  database:
    image: postgres:latest
    hostname: database
    container_name: database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=darthvader
      - POSTGRES_PASSWORD=iamyourfather
      - POSTGRES_DB=animals
    networks:
        - animals

  server:
    image: animals:latest
    hostname: server
    container_name: server
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://darthvader:iamyourfather@database:5432/animals
    networks:
      - animals
